source 'https://rubygems.org'

gem 'appium_lib'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.3'
gem 'appium_lib_core'
gem 'cucumber'
gem 'pry'
gem 'capybara'
gem 'appium_capybara'
gem 'faker'
